/**
 * Core cash-flow analysis tests — every headline assertion is an external
 * anchor generated by an independent closed-form script
 * (~/.hermes/scripts/anchors-finance2.py), cross-checked against published
 * references: the Excel IRR documentation example (8.663095%), the classic
 * two-IRR case (NPV(10%) = NPV(20%) = 0), and exact payback interpolation.
 *
 * @module dsh-finance/test
 */

import { describe, expect, it } from 'vitest'
import {
  analyzeCashflows,
  countSignChanges,
  discountedPayback,
  findIrr,
  npvAt,
  simplePayback,
} from '../src/cashflow.ts'

function analyze(flows: number[], rate?: number) {
  const result = analyzeCashflows(flows, rate)
  if (!('periods' in result)) throw new Error(`unexpected invalid: ${result.reason}`)
  return result
}

describe('net present value', () => {
  it('matches the Excel IRR documentation example at 8%', () => {
    const r = analyze([-70000, 12000, 15000, 18000, 21000, 26000], 8)
    expect(r.npv).toBeCloseTo(1390.96, 2)
  })

  it('matches the closed-form 10% annuity anchor', () => {
    const r = analyze([-1000, 400, 400, 400, 400], 10)
    expect(r.npv).toBeCloseTo(267.95, 2)
  })

  it('zero discount rate is the plain sum', () => {
    const r = analyze([-1000, 400, 400, 400, 400], 0)
    expect(r.npv).toBe(600)
  })

  it('negative discount rates work', () => {
    const r = analyze([-1000, 400, 400, 400, 400], -5)
    expect(r.npv).toBeGreaterThan(600)
  })

  it('omits npv when no rate is given', () => {
    const r = analyze([-1000, 400, 400, 400, 400])
    expect('npv' in r).toBe(false)
  })
})

describe('internal rate of return', () => {
  it('matches the Excel IRR documentation example (8.663095%)', () => {
    const r = analyze([-70000, 12000, 15000, 18000, 21000, 26000])
    expect(r.irrPercent).toBeCloseTo(8.663095, 6)
  })

  it('one-period growth is the exact growth rate', () => {
    const r = analyze([-100, 110])
    expect(r.irrPercent).toBeCloseTo(10, 6)
  })

  it('matches the textbook 10.651681% anchor', () => {
    const r = analyze([-1000, 500, 400, 300])
    expect(r.irrPercent).toBeCloseTo(10.651681, 6)
  })

  it('matches the closed-form annuity anchors', () => {
    expect(analyze([-1000, 300, 300, 300, 300]).irrPercent).toBeCloseTo(7.713847, 6)
    expect(analyze([-5000, 2000, 2000, 2000]).irrPercent).toBeCloseTo(9.701026, 6)
    expect(analyze([-100, 60, 60, 60]).irrPercent).toBeCloseTo(36.309654, 6)
  })

  it('zero-interest flows give IRR 0', () => {
    const r = analyze([-1000, 1000])
    expect(r.irrPercent).toBeCloseTo(0, 6)
  })

  it('npv at the reported IRR is zero (self-consistency)', () => {
    const flows = [-70000, 12000, 15000, 18000, 21000, 26000]
    const irr = findIrr(flows)
    expect(irr).not.toBeNull()
    expect(Math.abs(npvAt(flows, irr as number))).toBeLessThan(1e-6)
  })

  it('reports no-sign-change flows without fabricating an IRR', () => {
    const r = analyze([100, 50, 50], 0)
    expect('irrPercent' in r).toBe(false)
    expect(r.irrNote).toMatch(/no sign change/)
    expect(r.npv).toBeCloseTo(200, 2)
  })

  it('flags the classic two-IRR case instead of reporting one root', () => {
    const r = analyze([-100, 230, -132], 8)
    expect(r.multipleIrrPossible).toBe(true)
    expect('irrPercent' in r).toBe(false)
    expect(r.irrNote).toMatch(/not be unique/)
    // NPV at 8%: -100 + 230/1.08 - 132/1.1664 = -0.2057...
    expect(r.npv).toBeCloseTo(-0.21, 2)
  })

  it('sign-change counting ignores zeros', () => {
    expect(countSignChanges([-1000, 0, 0, 4000])).toBe(1)
    expect(countSignChanges([-1000, 0, 500, 0, 400])).toBe(1)
    expect(countSignChanges([100, 0, 200])).toBe(0)
  })

  it('finds the root beyond the default bracket by extending it', () => {
    // root at 99900% — far outside (-100%, 1000%]
    const r = analyze([-1, 1000])
    expect(r.irrPercent).toBeCloseTo(99900, 0)
  })
})

describe('payback periods', () => {
  it('simple payback interpolates to 2.5 periods', () => {
    const r = analyze([-1000, 400, 400, 400, 400])
    expect(r.paybackPeriods).toBeCloseTo(2.5, 4)
  })

  it('simple payback interpolates to 3.3333 periods', () => {
    const r = analyze([-1000, 300, 300, 300, 300])
    expect(r.paybackPeriods).toBeCloseTo(3.3333, 4)
  })

  it('discounted payback matches the closed-form 3.0193 anchor', () => {
    const r = analyze([-1000, 400, 400, 400, 400], 10)
    expect(r.discountedPaybackPeriods).toBeCloseTo(3.0193, 3)
  })

  it('omits payback fields when flows never cross zero', () => {
    const r = analyze([100, 50, 50], 10)
    expect('paybackPeriods' in r).toBe(false)
    expect('discountedPaybackPeriods' in r).toBe(false)
  })

  it('omits discounted payback when no rate is given', () => {
    const r = analyze([-1000, 400, 400, 400, 400])
    expect('discountedPaybackPeriods' in r).toBe(false)
    expect(r.paybackPeriods).toBeCloseTo(2.5, 4)
  })
})

describe('summaries and validation', () => {
  it('summarizes inflows, outflows and net cash flow', () => {
    const r = analyze([-1000, 400, 400, 400, 400])
    expect(r.periods).toBe(4)
    expect(r.totalInflow).toBe(1600)
    expect(r.totalOutflow).toBe(1000)
    expect(r.netCashflow).toBe(600)
  })

  it('rejects invalid inputs with a reason', () => {
    const cases: Array<[unknown, number | undefined]> = [
      [[], undefined],
      [[100], undefined],
      [[100, 200, Number.NaN], undefined],
      [[100, 200], -101],
      ['not-an-array', undefined],
    ]
    for (const [flows, rate] of cases) {
      const result = analyzeCashflows(flows as number[], rate)
      expect('periods' in result, `expected invalid for ${JSON.stringify(flows)}`).toBe(false)
      expect('reason' in result).toBe(true)
      expect((result as { reason: string }).reason.length).toBeGreaterThan(0)
    }
  })

  it('simplePayback and discountedPayback return null without a crossing', () => {
    expect(simplePayback([100, 50])).toBeNull()
    expect(discountedPayback([100, 50], 0.1)).toBeNull()
  })
})
