/**
 * Core retirement-planning tests — every headline assertion is an external
 * anchor generated by an independent closed-form script
 * (an independent anchors script), cross-checked against the
 * existing loan_payment mortgage-table anchor (sustainable withdrawal is the
 * PMT closed form, so $300k @ 4% / 30y must give $1,432.25) and the classic
 * 4%-rule intuition (interest-only withdrawals never deplete).
 *
 * @module dsh-finance/test
 */

import { describe, expect, it } from 'vitest'
import { planRetirement } from '../src/retirement.ts'

function plan(input: Parameters<typeof planRetirement>[0]) {
  const result = planRetirement(input)
  if (!('principal' in result)) throw new Error(`unexpected invalid: ${result.reason}`)
  return result
}

describe('sustainable monthly withdrawal', () => {
  it('matches the closed-form 1M @ 4% / 30y anchor (4774.15)', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, years: 30 })
    expect(r.sustainableMonthlyWithdrawal).toBeCloseTo(4774.15, 2)
    expect(r.horizonMonths).toBe(360)
    expect(r.totalWithdrawn).toBeCloseTo(1_718_694, 0)
    expect(r.interestEarned).toBeCloseTo(718_694, 0)
  })

  it('cross-checks the loan_payment mortgage-table anchor (300k → 1432.25)', () => {
    const r = plan({ principal: 300_000, annualRatePercent: 4, years: 30 })
    expect(r.sustainableMonthlyWithdrawal).toBeCloseTo(1432.25, 2)
  })

  it('zero return is principal / months', () => {
    expect(plan({ principal: 1_000_000, annualRatePercent: 0, years: 30 }).sustainableMonthlyWithdrawal).toBeCloseTo(2777.78, 2)
    expect(plan({ principal: 12_000, annualRatePercent: 0, years: 1 }).sustainableMonthlyWithdrawal).toBe(1000)
  })

  it('negative real returns still solve (loss is reported)', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: -1, years: 30 })
    expect(r.sustainableMonthlyWithdrawal).toBeGreaterThan(0)
    expect(r.interestEarned).toBeLessThan(0)
  })

  it('omits exhaustion fields when only years are given', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, years: 30 })
    expect('monthsToExhaust' in r).toBe(false)
    expect('neverExhausts' in r).toBe(false)
    expect('withdrawalRatePercent' in r).toBe(false)
  })
})

describe('time to exhaustion', () => {
  it('matches the closed-form 1M @ 4% / 4000 per month anchor', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 4000 })
    expect(r.monthsToExhaust).toBeCloseTo(538.42, 2)
    expect(r.yearsToExhaust).toBeCloseTo(44.87, 2)
    expect(r.withdrawalRatePercent).toBeCloseTo(4.8, 6)
  })

  it('interest-only withdrawals never deplete (4%-rule intuition)', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 3333.33 })
    expect(r.neverExhausts).toBe(true)
    expect('monthsToExhaust' in r).toBe(false)
    expect(r.withdrawalRatePercent).toBeCloseTo(4.0, 1)
  })

  it('withdrawing the exact sustainable amount depletes at the horizon', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 4774.152955 })
    expect(r.monthsToExhaust).toBeCloseTo(360, 1)
  })

  it('zero return exhausts in principal / withdrawal months', () => {
    const r = plan({ principal: 100_000, annualRatePercent: 0, monthlyWithdrawal: 2000 })
    expect(r.monthsToExhaust).toBe(50)
    expect(r.yearsToExhaust).toBeCloseTo(4.17, 2)
  })

  it('negative real returns exhaust sooner (closed-form anchor)', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: -1, monthlyWithdrawal: 3000 })
    expect(r.monthsToExhaust).toBeCloseTo(294.02, 2)
  })

  it('omits sustainable fields when only a withdrawal is given', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 4000 })
    expect('sustainableMonthlyWithdrawal' in r).toBe(false)
    expect('totalWithdrawn' in r).toBe(false)
  })
})

describe('combined mode (withdrawal + horizon)', () => {
  it('reports that a 4.8% withdrawal lasts 30 years', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 4000, years: 30 })
    expect(r.lastsHorizon).toBe(true)
  })

  it('reports that a 6% withdrawal does not last 30 years', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 5000, years: 30 })
    expect(r.lastsHorizon).toBe(false)
    expect(r.yearsToExhaust).toBeLessThan(30)
  })

  it('a never-depleting withdrawal always lasts the horizon', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 3000, years: 30 })
    expect(r.lastsHorizon).toBe(true)
    expect(r.neverExhausts).toBe(true)
  })

  it('computes both exhaustion and sustainable withdrawal together', () => {
    const r = plan({ principal: 1_000_000, annualRatePercent: 4, monthlyWithdrawal: 4000, years: 20 })
    expect(r.monthsToExhaust).toBeCloseTo(538.42, 2)
    expect(r.sustainableMonthlyWithdrawal).toBeCloseTo(6059.8, 1)
  })
})

describe('validation', () => {
  it('rejects invalid inputs with a reason', () => {
    const cases: Parameters<typeof planRetirement>[0][] = [
      { principal: 0, annualRatePercent: 4, monthlyWithdrawal: 1000 },
      { principal: 100, annualRatePercent: -101, monthlyWithdrawal: 10 },
      { principal: 100, annualRatePercent: 4, monthlyWithdrawal: 0 },
      { principal: 100, annualRatePercent: 4, years: 0 },
      { principal: 100, annualRatePercent: 4, years: 300 },
      { principal: 100, annualRatePercent: 4 },
      { principal: Number.NaN, annualRatePercent: 4, years: 30 },
    ]
    for (const input of cases) {
      const result = planRetirement(input)
      expect('principal' in result, `expected invalid for ${JSON.stringify(input)}`).toBe(false)
      expect('reason' in result).toBe(true)
      expect((result as { reason: string }).reason.length).toBeGreaterThan(0)
    }
  })
})
